In [2]:
import numpy as np

In [3]:
np.__version__

'1.19.1'

In [4]:
print(np.ndarray)

<class 'numpy.ndarray'>


In [5]:
np.ndarray.__name__

'ndarray'

In [6]:
type(np.ndarray.var)

method_descriptor

In [7]:
for i in dir(np.ndarray):
    if not i.startswith("_"):
        if type(np.ndarray.__dict__[i]) != type(np.ndarray.var):
            print(i)

T
base
ctypes
data
dtype
flags
flat
imag
itemsize
nbytes
ndim
real
shape
size
strides


In [8]:
for i in dir(np.ndarray):
    print(i)

T
__abs__
__add__
__and__
__array__
__array_finalize__
__array_function__
__array_interface__
__array_prepare__
__array_priority__
__array_struct__
__array_ufunc__
__array_wrap__
__bool__
__class__
__complex__
__contains__
__copy__
__deepcopy__
__delattr__
__delitem__
__dir__
__divmod__
__doc__
__eq__
__float__
__floordiv__
__format__
__ge__
__getattribute__
__getitem__
__gt__
__hash__
__iadd__
__iand__
__ifloordiv__
__ilshift__
__imatmul__
__imod__
__imul__
__index__
__init__
__init_subclass__
__int__
__invert__
__ior__
__ipow__
__irshift__
__isub__
__iter__
__itruediv__
__ixor__
__le__
__len__
__lshift__
__lt__
__matmul__
__mod__
__mul__
__ne__
__neg__
__new__
__or__
__pos__
__pow__
__radd__
__rand__
__rdivmod__
__reduce__
__reduce_ex__
__repr__
__rfloordiv__
__rlshift__
__rmatmul__
__rmod__
__rmul__
__ror__
__rpow__
__rrshift__
__rshift__
__rsub__
__rtruediv__
__rxor__
__setattr__
__setitem__
__setstate__
__sizeof__
__str__
__sub__
__subclasshook__
__truediv__
__xor__
all
any
argmax

In [9]:
l = [1, 2, 3, 4]
a = np.array(l)
a

array([1, 2, 3, 4])

In [10]:
type(a)

numpy.ndarray

In [12]:
t = (1, 2, 3, 4)
b = np.array(t)
type(b)
b

array([1, 2, 3, 4])

In [13]:
a.data

In [14]:
a.data.obj

array([1, 2, 3, 4])

In [15]:
type(a.data.obj)

numpy.ndarray

In [16]:
c = b
c.base is b.base

True

In [17]:
c[0] = 100
c

array([100,   2,   3,   4])

In [18]:
b

array([100,   2,   3,   4])

In [19]:
d = np.array(b)
d[0] = 99
d

array([99,  2,  3,  4])

In [20]:
b

array([100,   2,   3,   4])

In [21]:
e = np.array(l, dtype=np.float)
e

array([1., 2., 3., 4.])

In [22]:
e.dtype

dtype('float64')

In [23]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
a2.shape

(2, 3)

In [25]:
a2.ndim

2

In [26]:
a2.dtype

dtype('int64')

In [27]:
a2.itemsize

8

In [28]:
a2.size

6

In [29]:
a2.strides

(24, 8)

In [30]:
a2.flatten()

array([1, 2, 3, 4, 5, 6])

In [31]:
a2.ravel()

array([1, 2, 3, 4, 5, 6])

In [32]:
a

array([1, 2, 3, 4])

In [33]:
l

[1, 2, 3, 4]

In [34]:
a[0]

1

In [35]:
l[0]

1

In [36]:
l2 = [[1, 2, 3], [4, 5, 6]]
l2

[[1, 2, 3], [4, 5, 6]]

In [37]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
try :
    l2[0, 1]
except Exception as e:
    print(e)

list indices must be integers or slices, not tuple


In [39]:
l2[0][1]

2

In [40]:
a2[0, 1]

2

In [41]:
type(a2[0, 1])

numpy.int64

In [42]:
a2[0, 1].item()

2

In [43]:
type(a2[0, 1].item())

int

In [44]:
a2[0, 1].real

2

In [45]:
a2[0, 1].imag

0