In [6]:
import numpy as np

In [7]:
na = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
na

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [8]:
na.ndim

3

In [9]:
na.shape

(2, 2, 3)

In [10]:
na[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
na[0].shape

(2, 3)

In [12]:
na.__array_interface__

{'data': (140310018412384, False),
 'strides': None,
 'descr': [('', '<i8')],
 'typestr': '<i8',
 'shape': (2, 2, 3),
 'version': 3}

In [13]:
na.strides

(48, 24, 8)

In [14]:
na.__array_interface__['data'][0]

140310018412384

In [15]:
len(na.data.tobytes())

96

In [16]:
na.data.tolist()

[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]

In [17]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [18]:
a.data

In [19]:
mem = memoryview(a)
mem

In [20]:
a.data[0]

1

In [21]:
a[0]

1

In [22]:
a.data.obj

array([1, 2, 3, 4])

In [23]:
a

array([1, 2, 3, 4])

In [24]:
a.data.obj[0]

1

In [25]:
a.dtype

dtype('int64')

In [26]:
a.itemsize

8

In [27]:
a.data.hex()

'0100000000000000020000000000000003000000000000000400000000000000'

In [28]:
b = np.array([999, 9999, 99999, 999999])
b.data.hex()[:8]

'e7030000'

In [29]:
hex(999)

'0x3e7'

In [30]:
int('0x3e7', 16)

999

In [31]:
divmod(999, 16)

(62, 7)

In [32]:
divmod(62, 16)

(3, 14)

In [33]:
divmod(3, 16)

(0, 3)

In [34]:
a.size

4

In [35]:
for i in range(a.size):
    print(a[i])

1
2
3
4


In [36]:
a.flat

In [37]:
for i in a.flat:
    print(i)

1
2
3
4


In [38]:
c = np.array([1, 2, 3, 4], dtype=np.float)

In [39]:
c

array([1., 2., 3., 4.])

In [40]:
x = np.frombuffer(c)
x

array([1., 2., 3., 4.])

In [42]:
x.dtype

dtype('float64')

In [43]:
x[0]

1.0

In [44]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [45]:
x.base is c

True

In [46]:
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False