In [1]:
import numpy as np

In [3]:
np.ndarray.__bases__

(object,)

In [4]:
np.matrix.__bases__

(numpy.ndarray,)

In [5]:
l1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
l1.shape

(8,)

In [7]:
m1 = np.matrix([1, 2, 3, 4, 5, 6, 7, 8])
m1.shape

(1, 8)

In [8]:
l2 = l1.reshape(2, 4)
l2.shape

(2, 4)

In [9]:
m2 = m1.reshape(2, 4)
m2.shape

(2, 4)

In [10]:
l3 = l2.reshape(2, 2, 2)

In [11]:
l3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
try:
    m3 = m2.reshape(2, 2, 2)
except Exception as e:
    print('예외', e)

예외 shape too large to be a matrix.


In [13]:
m2_1 = np.asmatrix(l1).reshape(2, 4)
m2_1

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [15]:
l2 * l2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [16]:
try:
    m2 * m2
except Exception as e:
    print(e)

shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)


In [17]:
np.multiply(m2, m2)

matrix([[ 1,  4,  9, 16],
        [25, 36, 49, 64]])

In [18]:
nd_ = set(dir(np.ndarray))
md_ = set(dir(np.matrix))
md_ - nd_

{'A',
 'A1',
 'H',
 'I',
 '__dict__',
 '__module__',
 '_align',
 '_collapse',
 'getA',
 'getA1',
 'getH',
 'getI',
 'getT'}

In [19]:
m4 = np.mat('1 2; 3 4')
m4

matrix([[1, 2],
        [3, 4]])

In [20]:
m4.A

array([[1, 2],
       [3, 4]])

In [21]:
m4.getA()

array([[1, 2],
       [3, 4]])

In [22]:
m4.H

matrix([[1, 3],
        [2, 4]])

In [23]:
m4.T

matrix([[1, 3],
        [2, 4]])

In [24]:
from numpy import linalg

In [25]:
linalg.inv(m4)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [26]:
m4.I

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [27]:
m2

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [28]:
try:
    linalg.inv(m2)
except Exception as e:
    print(e)

Last 2 dimensions of the array must be square


In [29]:
m2.I

matrix([[-5.50000000e-01,  2.50000000e-01],
        [-2.25000000e-01,  1.25000000e-01],
        [ 1.00000000e-01, -2.10437669e-17],
        [ 4.25000000e-01, -1.25000000e-01]])