In [1]:
import numpy as np

In [2]:
v = np.arange(10)

In [3]:
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
v.dtype

dtype('int64')

In [5]:
v1 = np.arange(10.5, 20.5, 0.5)

In [6]:
v1

array([10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [7]:
v1.dtype

dtype('float64')

In [8]:
v1.size

20

In [9]:
v3 = np.arange(60).reshape(6, 10)

In [10]:
v3.shape

(6, 10)

In [11]:
v3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [12]:
v4 = np.arange(60).reshape(3, 4, 5)

In [13]:
v4.shape

(3, 4, 5)

In [14]:
v4

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [15]:
la = np.linspace(1, 10 , 10)

In [16]:
la

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
la.dtype

dtype('float64')

In [18]:
la2 = np.linspace(1, 2, 10, retstep=True)

In [19]:
la2

(array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ]),
 0.1111111111111111)

In [20]:
la2[0].size

10

In [21]:
lo = np.logspace(0, 2, 4)

In [22]:
lo

array([  1.        ,   4.64158883,  21.5443469 , 100.        ])

In [23]:
la2 = np.linspace(0, 2, 4)

In [24]:
la2

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [25]:
for i in la2:
    print(np.power(10, i))

1.0
4.641588833612778
21.544346900318832
100.0
