In [1]:
import numpy as np

In [2]:
v = np.arange(3, 5)

In [3]:
v

array([3, 4])

In [4]:
v_p = np.power(v, 2)

In [5]:
v_p

array([ 9, 16])

In [6]:
v_r = np.sqrt(np.sum(v_p))

In [7]:
v_r

5.0

In [8]:
np.hypot(v[0], v[1])

5.0

In [9]:
np.linalg.norm(v)

5.0

In [10]:
e1 = np.array([1, 0, 0])

In [11]:
np.linalg.norm(e1)

1.0

In [12]:
e2 = np.array([0, 1, 0])

In [13]:
np.linalg.norm(e2)

1.0

In [14]:
e3 = np.array([0, 0, 1])

In [15]:
np.linalg.norm(e3)

1.0

In [16]:
v_3 = np.array([1, 2, 3])

In [17]:
v_3_n = np.linalg.norm(v_3)

In [18]:
v_3_n

3.7416573867739413

In [19]:
v_3

array([1, 2, 3])

In [20]:
v_3_u = v_3 / v_3_n

In [21]:
v_3_u

array([0.26726124, 0.53452248, 0.80178373])

In [22]:
np.linalg.norm(v_3_u)

1.0

In [23]:
def normal (v):
    return v / np.sqrt(np.dot(v, v))

In [24]:
v_4 = np.array([1, 2, 3, 4])

In [25]:
v_4_u = normal(v_4)

In [26]:
v_4_u

array([0.18257419, 0.36514837, 0.54772256, 0.73029674])

In [27]:
np.linalg.norm(v_4_u)

0.9999999999999999

In [28]:
np.round(np.linalg.norm(v_4_u), 10)

1.0