In [2]:
import numpy as np
v1 = np.array([1, 2, 3, 4])

In [3]:
np.linalg.matrix_rank(v1)

1

In [4]:
c = np.array([[1, 2, 4], [2, 4, 8]])

In [5]:
c

array([[1, 2, 4],
       [2, 4, 8]])

In [6]:
np.linalg.matrix_rank(c)

1

In [7]:
c1 = np.array([[1, 2, 4], [2, 4, 8], [3, 4, 5]])

In [8]:
np.linalg.matrix_rank(c1)

2

In [9]:
np.linalg.det(c1)

0.0

In [10]:
c1[0] *2 - c1[1]

array([0, 0, 0])

In [11]:
c2 = np.array([[1, 3, 4], [1, 8, 5], [2, 3, 4]])

In [12]:
np.linalg.matrix_rank(c2)

3

In [13]:
np.linalg.det(c2)

-17.0

In [14]:
np.linalg.matrix_rank(c2.T)

3

In [15]:
c3 = np.array([[1, 2, 3], [4, 5, 6], [0, 0, 0]])

In [16]:
c3

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

In [17]:
np.linalg.matrix_rank(c3)

2

In [18]:
np.linalg.det(c3)

0.0