In [1]:
import numpy as np

In [2]:
x = np.array([1, 2])

In [3]:
x

array([1, 2])

In [4]:
y = np.expand_dims(x, axis=1)

In [5]:
y

array([[1],
       [2]])

In [6]:
z = np.expand_dims(x, axis=0)

In [7]:
z

array([[1, 2]])

In [8]:
z.ndim

2

In [9]:
x.ndim

1

In [10]:
y.ndim

2

In [11]:
x = np.array([[1, 4, 5], [4, 5, 6], [7, 8, 9]])

In [12]:
x

array([[1, 4, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
x.flatten()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

In [14]:
x.ravel()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

In [15]:
np.may_share_memory(x.flatten(), x)

False

In [16]:
np.may_share_memory(x.ravel(), x)

True