In [1]:
import numpy as np

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 8]])

In [7]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [8]:
a.shape

(3, 3)

In [9]:
np.trace(a)

14

In [10]:
a.trace()

14

In [11]:
b = np.array([[1, 0, 0], [0, 3, 0], [0, 0, 5]])

In [12]:
b

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [13]:
b.diagonal()

array([1, 3, 5])

In [14]:
np.diagonal(b)

array([1, 3, 5])

In [15]:
c = np.diag(np.arange(1, 4))

In [16]:
c

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [17]:
d = np.diag(np.arange(1, 4), k = 1)

In [18]:
d

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [19]:
e = np.diag(np.arange(1, 4), k = -1)

In [20]:
e

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

In [22]:
f = np.diag([[1, 2], [3, 4]])

In [23]:
f

array([1, 4])

In [26]:
g = np.diagonal([[1, 2], [3, 4]])

In [27]:
g

array([1, 4])

In [28]:
h = np.eye(3, 3)

In [29]:
h

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
i = np.eye(3, 3, k=1)

In [31]:
i

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [32]:
j = np.eye(3, 3, k=-1)

In [33]:
j

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [34]:
k = np.diag([4, 4, 4])

In [35]:
k

array([[4, 0, 0],
       [0, 4, 0],
       [0, 0, 4]])

In [36]:
k * 1/4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
l = np.identity(3)

In [38]:
l

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
s = np.arange(1, 10).reshape(3, 3)

In [40]:
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
s.dot(l)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])