In [1]:
import numpy as np

In [2]:
a = np.arange(6, 10)
a

array([6, 7, 8, 9])

In [3]:
b = np.arange(10, 14)
b

array([10, 11, 12, 13])

In [4]:
c = a * b
c

array([ 60,  77,  96, 117])

In [5]:
d = a[:, np.newaxis]
d

array([[6],
       [7],
       [8],
       [9]])

In [6]:
d.shape

(4, 1)

In [7]:
e = b[np.newaxis, :]
e

array([[10, 11, 12, 13]])

In [8]:
e.shape

(1, 4)

In [9]:
f = d @ e
f

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [10]:
d.dot(e)

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])