In [1]:
import numpy as np

In [2]:
a = np.arange(1, 10).reshape(3, 3)

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [5]:
np.tril(a, k=-1)

array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

In [6]:
b = np.arange(1, 10).reshape(3, 3)

In [7]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.triu(b)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [9]:
np.triu(b, k=1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

In [10]:
c = np.triu(b)

In [11]:
c

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [12]:
c.T

array([[1, 0, 0],
       [2, 5, 0],
       [3, 6, 9]])

In [13]:
d = np.tril(b)

In [14]:
d.T

array([[1, 4, 7],
       [0, 5, 8],
       [0, 0, 9]])

In [15]:
d

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [16]:
d*d

array([[ 1,  0,  0],
       [16, 25,  0],
       [49, 64, 81]])

In [17]:
c*c

array([[ 1,  4,  9],
       [ 0, 25, 36],
       [ 0,  0, 81]])

In [18]:
d * c

array([[ 1,  0,  0],
       [ 0, 25,  0],
       [ 0,  0, 81]])