In [1]:
import numpy as np

In [2]:
a = np.arange(1, 10).reshape(3, 3)

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
b = np.eye(3, dtype='int')

In [5]:
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [6]:
np.dot(a, b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
c = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])

In [8]:
np.dot(a, c)

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])