In [1]:
import numpy as np

In [2]:
z = np.zeros((3, 3))

In [3]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
z0 = np.zeros(3)

In [5]:
z0

array([0., 0., 0.])

In [6]:
z1 = np.zeros_like(np.arange(1, 10).reshape(3, 3))

In [7]:
z1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
e = np.empty(3)

In [9]:
e

array([0., 0., 0.])

In [11]:
e33 = np.empty((3, 3))

In [12]:
e33

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])