In [1]:
import numpy as np

In [2]:
X = np.array([[1, 2, 3], [2, 3, 5], [3, 5, 6]])

In [3]:
X

array([[1, 2, 3],
       [2, 3, 5],
       [3, 5, 6]])

In [4]:
X.T

array([[1, 2, 3],
       [2, 3, 5],
       [3, 5, 6]])

In [5]:
np.array_equal(X, X.T)

True

In [6]:
np.array_equiv(X, X.T)

True

In [7]:
X + X.T

array([[ 2,  4,  6],
       [ 4,  6, 10],
       [ 6, 10, 12]])

In [8]:
np.dot(X, X.T)

array([[14, 23, 31],
       [23, 38, 51],
       [31, 51, 70]])

In [9]:
a = np.transpose(np.dot(X, X.T))

In [10]:
b = np.dot(X.T, X)

In [11]:
a == b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [12]:
Y = np.array([[0, 2, -3], [-2, 0, 5], [3, -5, 0]])

In [13]:
Y

array([[ 0,  2, -3],
       [-2,  0,  5],
       [ 3, -5,  0]])

In [14]:
Y + Y.T

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
Y.T == -Y

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [16]:
Y - Y.T

array([[  0,   4,  -6],
       [ -4,   0,  10],
       [  6, -10,   0]])

In [17]:
np.dot(Y, Y.T)

array([[ 13, -15, -10],
       [-15,  29,  -6],
       [-10,  -6,  34]])

In [18]:
np.dot(Y.T, Y)

array([[ 13, -15, -10],
       [-15,  29,  -6],
       [-10,  -6,  34]])