In [1]:
import numpy as np

In [2]:
a2 = np.array([1, 2, 3, 4])
a2

array([1, 2, 3, 4])

In [3]:
a2 = a2.reshape(2, 2)
a2

array([[1, 2],
       [3, 4]])

In [4]:
np.sum(a2)

10

In [5]:
np.sum(a2, axis=0)

array([4, 6])

In [6]:
np.sum(a2, axis=1)

array([3, 7])

In [7]:
a3 = np.arange(1, 9)
a3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
a3 = a3.reshape(2, 2, 2)
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
a3.shape

(2, 2, 2)

In [10]:
a3[0]

array([[1, 2],
       [3, 4]])

In [11]:
a3[1]

array([[5, 6],
       [7, 8]])

In [12]:
np.sum(a3)

36

In [13]:
np.sum(a3, axis=0)

array([[ 6,  8],
       [10, 12]])

In [14]:
np.sum(a3, axis=1)

array([[ 4,  6],
       [12, 14]])

In [15]:
np.sum(a3, axis=2)

array([[ 3,  7],
       [11, 15]])

In [16]:
a = np.array([4, 5])
a.shape

(2,)

In [17]:
b = np.array([3, 4, 6])
b.shape

(3,)

In [18]:
try:
    a + b
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (2,) (3,) 


In [19]:
a = np.append(a, [6])
a.shape

(3,)

In [20]:
a + b

array([ 7,  9, 12])

In [21]:
a2 = np.array([[1, 2, 3], [3, 4, 5]])
b2 = np.array([1, 2])

In [22]:
try:
    a2 + b2
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (2,3) (2,) 


In [23]:
b2 = np.append(b2, [3])
b2.shape

(3,)

In [24]:
a2 + b2

array([[2, 4, 6],
       [4, 6, 8]])