In [1]:
import numpy as np

In [2]:
B = np.arange(9).reshape(3, 3)

In [3]:
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
B.shape

(3, 3)

In [5]:
B[0, :]

array([0, 1, 2])

In [6]:
B[0]

array([0, 1, 2])

In [7]:
B[:, 0]

array([0, 3, 6])

In [8]:
B[:2, 1:]

array([[1, 2],
       [4, 5]])

In [9]:
B[::2, ::2]

array([[0, 2],
       [6, 8]])

In [10]:
B.flat

In [11]:
B.flat[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
B.flat[::2]

array([0, 2, 4, 6, 8])