In [1]:
import numpy as np

In [2]:
A = np.arange(1, 60, 5).reshape(3, 4)

In [3]:
A

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56]])

In [4]:
...

Ellipsis

In [5]:
type(...)

ellipsis

In [6]:
A[...]

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56]])

In [7]:
A[:2, ...]

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36]])

In [8]:
A[..., :2]

array([[ 1,  6],
       [21, 26],
       [41, 46]])

In [9]:
B = np.arange(16).reshape(2, 2, 2, 2)

In [10]:
B

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [11]:
B[..., 0]

array([[[ 0,  2],
        [ 4,  6]],

       [[ 8, 10],
        [12, 14]]])

In [12]:
B[..., 0].flatten()

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [13]:
B[:, :, :, 0]

array([[[ 0,  2],
        [ 4,  6]],

       [[ 8, 10],
        [12, 14]]])

In [14]:
B[:, :, :, 0].flatten()

array([ 0,  2,  4,  6,  8, 10, 12, 14])