In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
b = a
b

array([[1, 2],
       [3, 4]])

In [4]:
a is b

True

In [5]:
a is b.base

False

In [6]:
b[0] = 999
a

array([[999, 999],
       [  3,   4]])

In [7]:
b

array([[999, 999],
       [  3,   4]])

In [8]:
f = np.array([4, 5, 6, 7, 8])
e = f.copy()
e.base is None

True

In [9]:
g = f[:]
g.base

array([4, 5, 6, 7, 8])

In [10]:
g.base is f

True

In [11]:
np.may_share_memory(g, f)

True

In [12]:
g[1] = 99999
g

array([    4, 99999,     6,     7,     8])

In [13]:
f

array([    4, 99999,     6,     7,     8])

In [14]:
h = f.view()
h

array([    4, 99999,     6,     7,     8])

In [15]:
h.base is f

True

In [16]:
np.may_share_memory(h, f)

True

In [17]:
a = np.array([1, 3, 5, 7])
b = np.array(a, copy=True)
b.base is None

True

In [18]:
c = np.array(a)
c.base is None

True