In [1]:
import numpy as np

In [2]:
L = np.arange(0, 12).reshape(3, 4)

In [3]:
L

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
L[ L < 5 ]

array([0, 1, 2, 3, 4])

In [5]:
L% 3

array([[0, 1, 2, 0],
       [1, 2, 0, 1],
       [2, 0, 1, 2]])

In [6]:
L[ L% 3 > 0 ]

array([ 1,  2,  4,  5,  7,  8, 10, 11])

In [7]:
L.nonzero()

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]),
 array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))

In [8]:
L[ L.nonzero() ]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])