In [1]:
import numpy as np

In [2]:
aa = np.array([1, 2, 3, 4, 5, 6, 7])
aa_c = np.sort(aa, axis=0)
aa_c

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
aa_c.base is None

True

In [4]:
aa[6] = 0
aa.sort()
aa

array([0, 1, 2, 3, 4, 5, 6])

In [5]:
l = list(range(1, 10))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
index = 1
l.__getitem__(index)

2

In [8]:
index = slice(1, 3)
l.__getitem__(index)

[2, 3]

In [9]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
index = 1
a.__getitem__(index)

2

In [10]:
index = slice(1, 3)
a.__getitem__(index)

array([2, 3])

In [11]:
index = 1
a.__getitem__(index)

2

In [12]:
index = [1]
a.__getitem__(index)

array([2])

In [13]:
index = a < 4
index

array([ True,  True,  True, False, False, False, False])

In [14]:
a.__getitem__(index)

array([1, 2, 3])

In [15]:
index = a < 3
a.__setitem__(index, 9080)
a

array([9080, 9080,    3,    4,    5,    6,    7])