In [1]:
import numpy as np

In [2]:
L = np.random.randn(7, 4)

In [3]:
L

array([[-0.12644575,  0.55497972,  0.36492016, -0.41700679],
       [ 0.81908511,  1.74770581, -0.99455929,  1.45070344],
       [-1.30285247,  0.04319419,  0.92662564, -1.61392857],
       [ 0.32787945, -0.84831263, -1.36124985, -1.24118335],
       [ 0.49361661, -0.78482856, -0.38067673,  0.27882336],
       [ 0.5911281 ,  1.22736311, -0.64149868, -1.04282899],
       [ 0.77360257,  0.79421863, -0.13908674, -1.06051542]])

In [4]:
L < 0

array([[ True, False, False,  True],
       [False, False,  True, False],
       [ True, False, False,  True],
       [False,  True,  True,  True],
       [False,  True,  True, False],
       [False, False,  True,  True],
       [False, False,  True,  True]])

In [5]:
L[L < 0]

array([-0.12644575, -0.41700679, -0.99455929, -1.30285247, -1.61392857,
       -0.84831263, -1.36124985, -1.24118335, -0.78482856, -0.38067673,
       -0.64149868, -1.04282899, -0.13908674, -1.06051542])

In [6]:
L[L < 0] = 999

In [7]:
L

array([[9.99000000e+02, 5.54979719e-01, 3.64920156e-01, 9.99000000e+02],
       [8.19085110e-01, 1.74770581e+00, 9.99000000e+02, 1.45070344e+00],
       [9.99000000e+02, 4.31941907e-02, 9.26625644e-01, 9.99000000e+02],
       [3.27879450e-01, 9.99000000e+02, 9.99000000e+02, 9.99000000e+02],
       [4.93616612e-01, 9.99000000e+02, 9.99000000e+02, 2.78823359e-01],
       [5.91128102e-01, 1.22736311e+00, 9.99000000e+02, 9.99000000e+02],
       [7.73602567e-01, 7.94218635e-01, 9.99000000e+02, 9.99000000e+02]])

In [8]:
LC = L[ L == 999 ]

In [9]:
LC

array([999., 999., 999., 999., 999., 999., 999., 999., 999., 999., 999.,
       999., 999., 999.])

In [10]:
LC[0] = 1000

In [11]:
LC

array([1000.,  999.,  999.,  999.,  999.,  999.,  999.,  999.,  999.,
        999.,  999.,  999.,  999.,  999.])

In [12]:
L == 1000

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [13]:
LL = L

In [14]:
np.may_share_memory(LC, L)

False

In [15]:
np.may_share_memory(LL, L)

True