### 03 팬시검색(fancy indexing)

In [1]:
import numpy as np

In [6]:
x = np.arange(1, 15)

In [7]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
pos = np.array([10])

In [9]:
pos

array([10])

In [10]:
x[10]

11

In [11]:
x[pos]

array([11])

In [12]:
pos2 = np.array([1, 2, 2, 2])

In [13]:
x[pos2]

array([2, 3, 3, 3])

In [14]:
c = x[pos2]

In [15]:
np.may_share_memory(x, c)

False

In [16]:
y = x[:4]

In [17]:
np.may_share_memory(x, y)

True

In [18]:
len(x)

14

In [19]:
try:
    x[[15]]
except Exception as e :
    print(e)

index 15 is out of bounds for axis 0 with size 14


In [20]:
d = x[[-5, -4, -3, -2, -1]]

In [21]:
d

array([10, 11, 12, 13, 14])

In [22]:
d[0] = 100

In [23]:
x[-5]

10

In [24]:
x = np.arange(16).reshape(4, 4)

In [25]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
x[[3, 0]]

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3]])

In [27]:
x[[-1, -2]]

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11]])

In [28]:
x[[1, 2], [2, 3]]

array([ 6, 11])

In [29]:
a = np.array([[2, 3, 4, 5], [8, 9, 0, 1]])

In [30]:
a

array([[2, 3, 4, 5],
       [8, 9, 0, 1]])

In [31]:
a[[0, 1], [0, 1]]

array([2, 9])

In [32]:
a[tuple([[0, 1], [0, 1]])]

array([2, 9])

In [33]:
type(np.ix_)

function

In [34]:
a[np.ix_([0, 1], [0, 1])]

array([[2, 3],
       [8, 9]])