### 다차원 배열로 검색하기

In [1]:
import numpy as np

In [3]:
x = np.arange(10).reshape(2, 5)

In [4]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
x[tuple([[0, 1], [0, 1]])]

array([0, 6])

In [6]:
x[[[0, 1], [0, 1]], [0, 1]]

array([[0, 6],
       [0, 6]])