### 배열을 축소 및 확대하기


In [1]:
import numpy as np

##### 예제 1 차원의 축소

In [4]:
x = np.arange(9).reshape(3, 3)

In [5]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
a = x[1: , 1:]

In [7]:
a

array([[4, 5],
       [7, 8]])

In [8]:
np.may_share_memory(x, a)

True

In [9]:
b = x[1: , [1, 2]]

In [10]:
b

array([[4, 5],
       [7, 8]])

In [11]:
np.may_share_memory(x, b)

False

##### 예제 2 확대 검색하기

In [13]:
a = np.reshape(np.arange(10), (2, 5))

In [14]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
b = a[[1, 1, 1]]

In [16]:
b.shape

(3, 5)

In [17]:
b

array([[5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])

In [18]:
c = a[[1, 1, 1], np.newaxis]

In [19]:
c.shape

(3, 1, 5)

In [20]:
c

array([[[5, 6, 7, 8, 9]],

       [[5, 6, 7, 8, 9]],

       [[5, 6, 7, 8, 9]]])

In [21]:
d = a[np.newaxis, [1, 1, 1]]

In [22]:
d.shape

(1, 3, 5)

In [23]:
d

array([[[5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9]]])

In [24]:
tuple([[1, 1], [0, 1]])

([1, 1], [0, 1])

In [25]:
a[tuple([[1, 1], [0, 1]])]

array([5, 6])

In [26]:
tuple([[[1, 1], [0, 1]]])

([[1, 1], [0, 1]],)

In [27]:
a[tuple([[[1, 1], [0, 1]]])]

array([[[5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9]],

       [[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [28]:
e = a[[[1, 1], [0, 1]], :]

In [29]:
e.shape

(2, 2, 5)

In [30]:
e

array([[[5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9]],

       [[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [31]:
f = a[[[1, 1], [0, 1]], :1]

In [32]:
f.shape

(2, 2, 1)

In [33]:
f

array([[[5],
        [5]],

       [[0],
        [5]]])

In [34]:
g = a[[[1, 1], [0, 1]], [0]]

In [35]:
g.shape

(2, 2)

In [36]:
g

array([[5, 5],
       [0, 5]])